// Auto-generated module: auth
// Feature: Authentication/Authorization tools
// Generated by Phantom self-improvement engine

import { createHash, randomBytes } from "crypto";

/**
 * Auth tools — JWT decode, hash verify, token analysis.
 * Usage: @auth|decode|<jwt_token>
 *        @auth|hash|<password> [--algorithm=<sha256|sha512|md5>]
 *        @auth|random|<length>
 */
export default async function(input) {
  try {
    const args = (input || "").trim();
    if (!args) {
      return `[auth] Authentication Tools
Usage:
  @auth|decode|<jwt_token>        Decode a JWT (no signature verify)
  @auth|hash|<password>           Hash a password (default: sha256)
  @auth|hash|<password> --algo=sha512
  @auth|random|32                  Generate random hex string (N bytes)
  @auth|basic|user:pass            Encode Basic auth header

Examples:
  auth|decode|eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.dozjgNryP4J3jVmNHx0I
  auth|hash|mypassword --algo=sha512
  auth|random|16`;
    }

    const parts = args.split("|").map(s => s.trim());
    const command = parts[0];
    const data = parts.slice(1).join("|");

    switch (command) {
      case "decode": {
        const token = data;
        if (!token || !token.includes(".")) return `[auth] Invalid JWT format`;
        const segments = token.split(".");
        if (segments.length < 2) return `[auth] Invalid JWT format`;
        const decode = (s) => {
          try {
            return JSON.parse(Buffer.from(s.replace(/-/g, "+").replace(/_/g, "/"), "base64").toString("utf-8"));
          } catch { return { error: "Cannot decode" }; }
        };
        const header = decode(segments[0]);
        const payload = decode(segments[1]);
        const lines = [
          `[auth] JWT Decoded`,
          `── Header ──`,
          JSON.stringify(header, null, 2),
          `── Payload ──`,
          JSON.stringify(payload, null, 2),
        ];
        if (segments[2]) lines.push(`── Signature ──${segments[2].slice(0, 32)}...`);
        return lines.join("\n");
      }

      case "hash": {
        const algoMatch = args.match(/--algo=(\w+)/);
        const algo = algoMatch ? algoMatch[1] : "sha256";
        if (!["sha256", "sha512", "md5", "sha1"].includes(algo)) return `[auth] Unsupported algorithm: ${algo}. Use sha256, sha512, md5, or sha1.`;
        const hash = createHash(algo).update(data).digest("hex");
        return `[auth] ${algo} hash of "${data.slice(0, 50)}":
${hash}`;
      }

      case "random": {
        const len = parseInt(data) || 16;
        const hex = randomBytes(Math.ceil(len / 2)).toString("hex").slice(0, len);
        return `[auth] Random hex (${len} chars): ${hex}`;
      }

      case "basic": {
        // Encode Basic auth header value
        const encoded = Buffer.from(data).toString("base64");
        return `[auth] Basic Auth:
  Header: Authorization: Basic ${encoded}
  Value: ${data}`;
      }

      default:
        return `[auth] Unknown command: ${command}. Use @auth|--help for usage.`;
    }
  } catch (e) {
    return `[auth Error] ${e.message}`;
  }
};
