// Auto-generated module: cache
// Feature: Caching layer for tool outputs
// Generated by Phantom self-improvement engine

import fs from "fs";
import { resolve } from "path";
import { homedir } from "os";
import { createHash } from "crypto";

const CACHE_DIR = resolve(homedir(), ".config", "phantom", "cache");
const DEFAULT_TTL = 5 * 60 * 1000; // 5 minutes

/**
 * Cache layer — store and retrieve cached tool outputs.
 * Usage: @cache|get|<key>
 *        @cache|set|<key>|<value> [--ttl=<ms>]
 *        @cache|del|<key>
 *        @cache|clear
 *        @cache|stats
 */
export default async function(input) {
  try {
    if (!fs.existsSync(CACHE_DIR)) fs.mkdirSync(CACHE_DIR, { recursive: true });

    const args = (input || "").trim();

    if (!args) {
      return `[cache] Cache System
Usage:
  @cache|get|<key>                  Get cached value
  @cache|set|<key>|<value>          Set cached value (default TTL: 5min)
  @cache|del|<key>                  Delete cached entry
  @cache|clear                      Clear entire cache
  @cache|stats                      Show cache statistics

Used internally by Phantom to cache repeated tool outputs.`;
    }

    const cacheFile = resolve(CACHE_DIR, "registry.json");
    let registry = {};
    try {
      if (fs.existsSync(cacheFile)) registry = JSON.parse(fs.readFileSync(cacheFile, "utf-8"));
    } catch {}

    const parts = args.split("|").map(s => s.trim());
    const command = parts[0];

    switch (command) {
      case "get": {
        const key = parts.slice(1).join("|");
        if (!key) return `[cache] Usage: @cache|get|<key>`;
        const hashKey = createHash("md5").update(key).digest("hex");
        const entry = registry[hashKey];
        if (!entry) return `[cache] Cache miss for: ${key.slice(0, 60)}`;
        if (Date.now() - entry.ts > (entry.ttl || DEFAULT_TTL)) {
          delete registry[hashKey];
          fs.writeFileSync(cacheFile, JSON.stringify(registry, null, 2), "utf-8");
          return `[cache] Cache expired for: ${key.slice(0, 60)}`;
        }
        return `[cache] Cache hit for: ${key.slice(0, 60)}\n${entry.value.slice(0, 3000)}`;
      }

      case "set": {
        const separatorIdx = args.indexOf("|", args.indexOf("|") + 1);
        if (separatorIdx === -1) return `[cache] Usage: @cache|set|<key>|<value>`;
        const key = args.slice(4, separatorIdx).trim();
        const value = args.slice(separatorIdx + 1).trim();
        const ttlMatch = args.match(/--ttl=(\d+)/);
        const ttl = ttlMatch ? parseInt(ttlMatch[1]) * 1000 : DEFAULT_TTL;
        const hashKey = createHash("md5").update(key).digest("hex");
        registry[hashKey] = { key, ts: Date.now(), ttl, length: value.length };
        if (!fs.existsSync(CACHE_DIR)) fs.mkdirSync(CACHE_DIR, { recursive: true });
        fs.writeFileSync(resolve(CACHE_DIR, `${hashKey}.cache`), value, "utf-8");
        fs.writeFileSync(cacheFile, JSON.stringify(registry, null, 2), "utf-8");
        return `[cache] Cached (${value.length} chars, TTL: ${ttl / 1000}s)`;
      }

      case "del": {
        const dkey = parts.slice(1).join("|");
        const dhash = createHash("md5").update(dkey).digest("hex");
        if (registry[dhash]) {
          delete registry[dhash];
          const cachePath = resolve(CACHE_DIR, `${dhash}.cache`);
          if (fs.existsSync(cachePath)) fs.unlinkSync(cachePath);
          fs.writeFileSync(cacheFile, JSON.stringify(registry, null, 2), "utf-8");
          return `[cache] Deleted: ${dkey.slice(0, 60)}`;
        }
        return `[cache] Not found: ${dkey.slice(0, 60)}`;
      }

      case "clear": {
        const count = Object.keys(registry).length;
        if (fs.existsSync(CACHE_DIR)) {
          const files = fs.readdirSync(CACHE_DIR);
          for (const f of files) fs.unlinkSync(resolve(CACHE_DIR, f));
        }
        fs.writeFileSync(cacheFile, "{}", "utf-8");
        return `[cache] Cache cleared (${count} entries removed)`;
      }

      case "stats": {
        const count = Object.keys(registry).length;
        let totalSize = 0, validEntries = 0, expiredEntries = 0;
        for (const [k, v] of Object.entries(registry)) {
          const cachePath = resolve(CACHE_DIR, `${k}.cache`);
          if (fs.existsSync(cachePath)) totalSize += fs.statSync(cachePath).size;
          if (Date.now() - v.ts > (v.ttl || DEFAULT_TTL)) expiredEntries++;
          else validEntries++;
        }
        return `[cache] Cache Stats:
  Total entries: ${count}
  Valid: ${validEntries}
  Expired: ${expiredEntries}
  Disk size: ${(totalSize / 1024).toFixed(1)} KB
  Cache dir: ${CACHE_DIR}`;
      }

      default:
        return `[cache] Unknown command: ${command}. Use @cache|--help for usage.`;
    }
  } catch (e) {
    return `[cache Error] ${e.message}`;
  }
};
