// Auto-generated tool: checkForParameter
// Source: Learned from "check_for_parameter" — Project has a tool/function "check_for_parameter" that Phantom doesn't wrap
// Generated by Phantom self-improvement engine

export default async function(input) {
  try {
    const { execSync } = await import("child_process");
    const { resolve } = await import("path");
    const args = (input || "").trim();
    if (!args) {
      return `[checkForParameter] Usage: @checkForParameter|<args>
Feature: Project has a tool/function "check_for_parameter" that Phantom doesn't wrap
Examples:
  checkForParameter|--help
  checkForParameter|<target>`;
    }
    const result = execSync(`checkForParameter ${args}`, {
      encoding: "utf-8",
      timeout: 60000,
      maxBuffer: 1024 * 1024,
    });
    return result.trim() || "(no output)";
  } catch (e) {
    return `[checkForParameter Error] ${e.stderr?.slice(0, 500) || e.message}`;
  }
}
