// Auto-generated tool: command
// Source: Learned from "command" — Auto-detected missing wrapper from phantom.mjs
// Generated by Phantom self-improvement engine

export default async function(input) {
  try {
    const { execSync } = await import("child_process");
    const { resolve } = await import("path");
    const args = (input || "").trim();
    if (!args) {
      return `[command] Usage: @command|<args>
Feature: Auto-detected missing wrapper from phantom.mjs
Examples:
  command|--help
  command|<target>`;
    }
    const result = execSync(`command ${args}`, {
      encoding: "utf-8",
      timeout: 60000,
      maxBuffer: 1024 * 1024,
    });
    return result.trim() || "(no output)";
  } catch (e) {
    return `[command Error] ${e.stderr?.slice(0, 500) || e.message}`;
  }
}
