// Auto-generated module: database
// Feature: Database integration (SQLite)
// Generated by Phantom self-improvement engine

import { execSync } from "child_process";
import { resolve } from "path";

/**
 * SQLite database query tool.
 * Usage: @database|<path>|<query>
 * Uses sqlite3 CLI. Install: apt install sqlite3
 */
export default async function(input) {
  try {
    const parts = (input || "").split("|").map(s => s.trim());
    if (parts.length < 2) {
      return `[database] SQLite Database Tool
Usage: @database|<db_path>|<sql_query>
Examples:
  database|test.db|SELECT * FROM users LIMIT 10;
  database|/tmp/data.db|.tables
  database|--tables|test.db                  List tables

Requires: sqlite3 CLI (apt install sqlite3)`;
    }

    const dbPath = parts[0];
    const query = parts.slice(1).join("|");

    // Check sqlite3 availability
    try {
      execSync("which sqlite3", { encoding: "utf-8", timeout: 3000 });
    } catch {
      return `[database] sqlite3 not found. Install: apt install sqlite3`;
    }

    const escapedQuery = query.replace(/'/g, "'\\''");
    const result = execSync(`sqlite3 -header -column "${dbPath}" '${escapedQuery}'`, {
      encoding: "utf-8",
      timeout: 30000,
      maxBuffer: 1024 * 1024,
    }).trim();

    return result || "(empty result)";
  } catch (e) {
    return `[database Error] ${e.stderr?.slice(0, 500) || e.message}`;
  }
};
