// Auto-generated tool: init
// Source: Learned from "__init__" — Project has a tool/function "__init__" that Phantom doesn't wrap
// Generated by Phantom self-improvement engine

export default async function(input) {
  try {
    const { execSync } = await import("child_process");
    const { resolve } = await import("path");
    const args = (input || "").trim();
    if (!args) {
      return `[init] Usage: @init|<args>
Feature: Project has a tool/function "__init__" that Phantom doesn't wrap
Examples:
  init|--help
  init|<target>`;
    }
    const result = execSync(`init ${args}`, {
      encoding: "utf-8",
      timeout: 60000,
      maxBuffer: 1024 * 1024,
    });
    return result.trim() || "(no output)";
  } catch (e) {
    return `[init Error] ${e.stderr?.slice(0, 500) || e.message}`;
  }
}
