// Auto-generated module: ipc
// Feature: Inter-process communication utilities
// Generated by Phantom self-improvement engine

import { spawn, execSync } from "child_process";
import { existsSync } from "fs";
import { isMainThread, parentPort, Worker } from "worker_threads";

/**
 * IPC tools — spawn processes, communicate via workers.
 * Usage: @ipc|exec|<command>
 *        @ipc|bg|<command>          Start background process
 *        @ipc|ps                    List child processes
 */
export default async function(input) {
  try {
    const args = (input || "").trim();

    if (!args) {
      return `[ipc] IPC Utilities
Usage:
  @ipc|exec|<command>            Execute and capture output
  @ipc|bg|<command>              Start background process
  @ipc|ps                        List Phantom child processes

For multi-process coordination and long-running tasks.`;
    }

    const parts = args.split("|").map(s => s.trim());
    const command = parts[0];
    const rest = parts.slice(1).join("|");

    switch (command) {
      case "exec": {
        if (!rest) return `[ipc] Usage: @ipc|exec|<shell command>`;
        // Use shell for full command support
        const result = execSync(rest, {
          encoding: "utf-8",
          timeout: 60000,
          maxBuffer: 1024 * 1024,
        });
        return `[ipc] Executed:
${rest}
── Output ──
${result.trim().slice(0, 4000) || "(empty)"}`;
      }

      case "bg": {
        if (!rest) return `[ipc] Usage: @ipc|bg|<command>`;
        const proc = spawn("sh", ["-c", rest], {
          stdio: ["ignore", "pipe", "pipe"],
          detached: true,
        });
        let out = "";
        proc.stdout.on("data", d => { out += d.toString(); });
        proc.stderr.on("data", d => { out += d.toString(); });
        // Don't await — let it run in background
        return `[ipc] Started background process (PID: ${proc.pid})
Command: ${rest}`;
      }

      case "ps": {
        // List phantom-related processes
        const result = execSync("ps aux | grep -E 'node|phantom' | grep -v grep", {
          encoding: "utf-8",
          timeout: 5000,
        }).trim();
        if (!result) return `[ipc] No Phantom child processes found`;
        const lines = result.split("\n");
        return `[ipc] Child Processes (${lines.length}):
${lines.join("\n")}`;
      }

      default:
        return `[ipc] Unknown command: ${command}. Use @ipc|--help for usage.`;
    }
  } catch (e) {
    return `[ipc Error] ${e.message}`;
  }
};
