// Phantom learned module — auto-generated by evolve.mjs. Do not edit.
// Source: knowledge/channel_1790270002665.json
export default {
  "kind": "knowledge",
  "source": "channel_1790270002665.json",
  "tags": [
    "https___www_youtube_com_channel_ucuvkpem38w6pq8w5qygtppw_videos",
    "youtube",
    "channel",
    "learned"
  ],
  "created": "2026-09-24T17:13:22.665Z",
  "learnedAt": "2026-09-24T17:47:25.618Z",
  "data": {
    "tags": [
      "https___www_youtube_com_channel_ucuvkpem38w6pq8w5qygtppw_videos",
      "youtube",
      "channel",
      "learned"
    ],
    "content": "Channel: https://www.youtube.com/channel/UCUvkPEm38w6pq8w5QYgtPPw/videos\nURL: https://www.youtube.com/channel/UCUvkPEm38w6pq8w5QYgtPPw/videos\nVideos analyzed: 3/5\nTopics: How Hackers Crack Every Single Game! (EDUCATIONAL PURPOSES), The Best Way To Learn Networking, OPSEC: How To Stay Anonymous Online",
    "created": "2026-09-24T17:13:22.665Z"
  }
};
