// Auto-generated tool: main
// Source: Learned from "main" — Project has a tool/function "main" that Phantom doesn't wrap
// Generated by Phantom self-improvement engine

export default async function(input) {
  try {
    const { execSync } = await import("child_process");
    const { resolve } = await import("path");
    const args = (input || "").trim();
    if (!args) {
      return `[main] Usage: @main|<args>
Feature: Project has a tool/function "main" that Phantom doesn't wrap
Examples:
  main|--help
  main|<target>`;
    }
    const result = execSync(`main ${args}`, {
      encoding: "utf-8",
      timeout: 60000,
      maxBuffer: 1024 * 1024,
    });
    return result.trim() || "(no output)";
  } catch (e) {
    return `[main Error] ${e.stderr?.slice(0, 500) || e.message}`;
  }
}
