// Auto-generated tool: request
// Source: Learned from "request" — Project has a tool/function "request" that Phantom doesn't wrap
// Generated by Phantom self-improvement engine

export default async function(input) {
  try {
    const { execSync } = await import("child_process");
    const { resolve } = await import("path");
    const args = (input || "").trim();
    if (!args) {
      return `[request] Usage: @request|<args>
Feature: Project has a tool/function "request" that Phantom doesn't wrap
Examples:
  request|--help
  request|<target>`;
    }
    const result = execSync(`request ${args}`, {
      encoding: "utf-8",
      timeout: 60000,
      maxBuffer: 1024 * 1024,
    });
    return result.trim() || "(no output)";
  } catch (e) {
    return `[request Error] ${e.stderr?.slice(0, 500) || e.message}`;
  }
}
