// Auto-generated tool: responseTime
// Source: Learned from "response_time" — Project has a tool/function "response_time" that Phantom doesn't wrap
// Generated by Phantom self-improvement engine

export default async function(input) {
  try {
    const { execSync } = await import("child_process");
    const { resolve } = await import("path");
    const args = (input || "").trim();
    if (!args) {
      return `[responseTime] Usage: @responseTime|<args>
Feature: Project has a tool/function "response_time" that Phantom doesn't wrap
Examples:
  responseTime|--help
  responseTime|<target>`;
    }
    const result = execSync(`responseTime ${args}`, {
      encoding: "utf-8",
      timeout: 60000,
      maxBuffer: 1024 * 1024,
    });
    return result.trim() || "(no output)";
  } catch (e) {
    return `[responseTime Error] ${e.stderr?.slice(0, 500) || e.message}`;
  }
}
