// Auto-generated module: streaming
// Feature: Stream processing for large data
// Generated by Phantom self-improvement engine

import { createReadStream, createWriteStream, existsSync } from "fs";
import { resolve } from "path";
import { Transform } from "stream";

/**
 * Stream processing tool — process large files line-by-line.
 * Usage: @streaming|<input>|<transform> [--output=<path>]
 * Transforms: upper, lower, reverse, base64, count, grep:<pattern>
 */
export default async function(input) {
  try {
    const args = (input || "").trim();
    if (!args) {
      return `[streaming] Stream Processor
Process large files line-by-line without loading into memory.
Usage: @streaming|<file>|<transform> [--output=<outfile>]
Transforms:
  upper          Convert to uppercase
  lower          Convert to lowercase
  reverse        Reverse each line
  base64         Base64 encode each line
  count          Count lines/words/bytes
  grep:<pat>     Filter lines matching pattern
  sed:s/find/replace  Search and replace

Examples:
  streaming|large.log|grep:ERROR --output=errors.log
  streaming|data.txt|upper
  streaming|bigfile.csv|count`;
    }

    const parts = args.split("|").map(s => s.trim());
    const inputPath = parts[0] ? resolve(parts[0]) : null;
    const transform = parts[1] || "";
    const outMatch = args.match(/--output=([^\s]+)/);
    const outputPath = outMatch ? resolve(outMatch[1]) : null;

    if (!inputPath || !existsSync(inputPath)) return `[streaming] Input file not found: ${parts[0]}`;
    if (!transform) return `[streaming] No transform specified`;

    const stat = existsSync(inputPath);
    const size = stat ? fs.statSync(inputPath).size : 0;

    // Simple counter mode
    if (transform === "count") {
      return new Promise((resolvePromise) => {
        let lines = 0, words = 0, bytes = 0;
        const rs = createReadStream(inputPath, { encoding: "utf-8" });
        rs.on("data", chunk => {
          bytes += Buffer.byteLength(chunk, "utf-8");
          lines += (chunk.match(/\n/g) || []).length;
          words += chunk.split(/\s+/).filter(Boolean).length;
        });
        rs.on("end", () => resolvePromise(`[streaming] ${inputPath}\n  Lines: ${lines}\n  Words: ${words}\n  Bytes: ${bytes}\n  Size: ${(size / 1024).toFixed(1)} KB`));
        rs.on("error", e => resolvePromise(`[streaming Error] ${e.message}`));
      });
    }

    // Line-by-line transform mode
    return new Promise((resolvePromise) => {
      const outputs = [];
      const rs = createReadStream(inputPath, { encoding: "utf-8" });
      const rl = require("readline").createInterface({ input: rs });

      rl.on("line", line => {
        let result = line;
        switch (transform) {
          case "upper": result = line.toUpperCase(); break;
          case "lower": result = line.toLowerCase(); break;
          case "reverse": result = line.split("").reverse().join(""); break;
          case "base64": result = Buffer.from(line, "utf-8").toString("base64"); break;
          default:
            if (transform.startsWith("grep:")) {
              const pat = transform.slice(5);
              if (!line.includes(pat) && !new RegExp(pat).test(line)) return;
            } else if (transform.startsWith("sed:")) {
              const m = transform.match(/^sed:(.+?)\/(.+?)\/(.*)$/);
              if (m) result = line.replace(new RegExp(m[1], "g"), m[2]);
            }
        }
        outputs.push(result);
      });

      rl.on("close", () => {
        const text = outputs.join("\n");
        if (outputPath) {
          fs.writeFileSync(outputPath, text, "utf-8");
          resolvePromise(`[streaming] Processed ${outputs.length} lines → ${outputPath} (${text.length} chars)`);
        } else {
          const preview = text.slice(0, 3000);
          const truncated = text.length > 3000 ? `\n... (truncated, ${text.length} total chars)` : "";
          resolvePromise(`[streaming] ${inputPath} → ${outputs.length} lines\n${preview}${truncated}`);
        }
      });

      rl.on("error", e => resolvePromise(`[streaming Error] ${e.message}`));
    });
  } catch (e) {
    return `[streaming Error] ${e.message}`;
  }
};
