// Auto-generated module: websocket
// Feature: WebSocket client for real-time communication
// Generated by Phantom self-improvement engine

/**
 * WebSocket client tool.
 * Usage: @websocket|<url> [--send=<message>] [--listen=<timeout_ms>]
 */
export default async function(input) {
  try {
    const args = (input || "").trim();
    if (!args) {
      return `[websocket] WebSocket Client
Usage: @websocket|<url> [--send=<message>]
Examples:
  websocket|wss://echo.websocket.org --send=hello
  websocket|wss://stream.binance.com:9443/ws/btcusdt --listen=5000

Sends an optional message and prints responses.
Requires Node.js native WebSocket (Node 22+) or 'ws' package.`;
    }

    const urlMatch = args.match(/https?:\/\/[^\s]+|wss?:\/\/[^\s]+/);
    if (!urlMatch) return `[websocket] No WebSocket URL found in: ${args}`;

    const url = urlMatch[0];
    const sendMatch = args.match(/--send=([^\s]+)/);
    const listenMatch = args.match(/--listen=(\d+)/);
    const listenMs = listenMatch ? parseInt(listenMatch[1]) : 3000;

    // Try native WebSocket (Node 22+)
    if (typeof WebSocket !== "undefined") {
      return await new Promise((resolve, reject) => {
        const ws = new WebSocket(url);
        const messages = [];
        const timeout = setTimeout(() => {
          ws.close();
          if (messages.length === 0) resolve(`[websocket] Connected to ${url} (no messages in ${listenMs}ms)`);
          else resolve(`[websocket] ${url}\nMessages (${messages.length}):\n${messages.join("\n")}`);
        }, listenMs);

        ws.onopen = () => {
          if (sendMatch) ws.send(sendMatch[1]);
        };
        ws.onmessage = (event) => {
          try {
            const parsed = JSON.parse(event.data);
            messages.push(typeof parsed === "object" ? JSON.stringify(parsed, null, 2).slice(0, 500) : event.data);
          } catch {
            messages.push(event.data.slice(0, 500));
          }
        };
        ws.onerror = (err) => { clearTimeout(timeout); resolve(`[websocket Error] ${err.message || "Connection failed"}`); };
        ws.onclose = () => clearTimeout(timeout);
      });
    }

    return `[websocket] WebSocket not available in this Node.js version. Install 'ws' package or upgrade to Node 22+.`;
  } catch (e) {
    return `[websocket Error] ${e.message}`;
  }
};
